### PR TITLE
fix error

### PR DESCRIPTION
**Pull request by Barbery**
in the newest version, nginx.conf path is wrong, and didn't load ngx_nchan_module.so

### CODE REVIEW

**Comment by Meroje** [comment]
My base image is using `/etc/nginx/nginx.conf` https://github.com/Meroje/alpine-nchan/blob/7aec803d3fd779fa74e700ff657c760a60a7af27/standard/Dockerfile#L13 and I see this example running fine. How are you running it that gets you an error ?

**Comment by Barbery** [comment]
Hi Meroje
I saw your DockerFile on the docker hub (https://hub.docker.com/r/meroje/alpine-nchan/~/dockerfile/), it seems use the default conf path. And I pull your latest image, the conf file is in the `/etc/nginx/conf/nginx.conf` path. Is there wrong version I install?

**Comment by Meroje** [comment]
That's an earlier version that I will deprecate at some point, the correct version for this example is from the [standard](https://github.com/Meroje/alpine-nchan/tree/master/standard) tag (you can tell with the [FROM line](https://github.com/Meroje/alpine-nchan-example/blob/1cad4fcabaaf796f35682edc28ad29130fb92c38/Dockerfile#L1)) which is itself based on the [nginxinc mainline/alpine dockerfile](https://github.com/nginxinc/docker-nginx/blob/25a3fc7343c6916fce1fba32caa1e8de8409d79f/mainline/alpine/Dockerfile)

**Comment by Barbery** [comment]
OK, thank you!

**Pull request closed without merging**
